export const insuranceOptionsByState = {
  AL: [
    { value: "aceSpecialtyBenefits", label: "ACI Specialty Benefits" },
    { value: "aetna", label: "Aetna" },
    { value: "allKids", label: "All Kids" },
    { value: "americanBehavioral", label: "American Behavioral" },
    { value: "anthem", label: "Anthem" },
    {
      value: "beaconHealthOptionsCarelon",
      label: "Beacon Health Options | Carelon",
    },
    {
      value: "bhsBehavioralHealthSystems",
      label: "BHS | Behavioral Health Systems",
    },
    { value: "blueCross", label: "Blue Cross" },
    { value: "blueShield", label: "Blue Shield" },
    { value: "blueCrossBlueShield", label: "BlueCross BlueShield" },
    { value: "ccnCommunityCareNetwork", label: "CCN | Community Care Network" },
    { value: "champva", label: "CHAMPVA" },
    { value: "cignaAndEvernorth", label: "Cigna and Evernorth" },
    {
      value: "esiEmployeeAssistanceGroup",
      label: "ESI Employee Assistance Group",
    },
    { value: "greatWestLife", label: "Great-West Life" },
    { value: "guardian", label: "Guardian" },
    { value: "horizonHealthCare", label: "Horizon Healthcare" },
    { value: "humana", label: "Humana" },
    { value: "magellan", label: "Magellan" },
    { value: "medicaid", label: "Medicaid" },
    { value: "medicare", label: "Medicare" },
    { value: "newDirections", label: "New Directions" },
    { value: "optum", label: "Optum" },
    { value: "phcsNetwork", label: "PHCS Network" },
    { value: "psychCare", label: "PsychCare" },
    { value: "triCare", label: "TRICARE" },
    { value: "unitedHealthCareUhcUbh", label: "UnitedHealthcare UHC | UBH" },
    {
      value: "vaCommunityCareNetworkCcn",
      label: "VA Community Care Network CCN",
    },
  ],
  MA: [
    { value: "aetna", label: "Aetna" },
    {
      value: "allWaysHealthPartners",
      label: "AllWays Health Partners | MGBHP",
    },
    { value: "anthem", label: "Anthem" },
    {
      value: "beaconHealthOptionsCarelon",
      label: "Beacon Health Options | Carelon",
    },

    { value: "blueCross", label: "Blue Cross" },
    { value: "blueShield", label: "Blue Shield" },
    { value: "blueCrossBlueShield", label: "BlueCross BlueShield" },
    { value: "bmcHealthNet", label: "BMC HealthNet" },
    { value: "choiceCareNetwork", label: "ChoiceCare Network" },
    { value: "cignaAndEvernorth", label: "Cigna and Evernorth" },
    { value: "commonwealthCareAlliance", label: "Commonwealth Care Alliance" },
    { value: "comPsych", label: "ComPsych" },
    {
      value: "esiEmployeeAssistanceGroup",
      label: "ESI Employee Assistance Group",
    },
    { value: "fallonHealth", label: "Fallon Health" },
    { value: "greatWestLife", label: "Great-West Life" },
    { value: "groupInsuranceCommission", label: "Group Insurance Commission" },
    { value: "harvardPilgrim", label: "Harvard Pilgrim" },
    { value: "healthNetMHN", label: "Health Net | MHN" },
    { value: "healthNewEngland", label: "Health New England (HNE)" },
    { value: "healthyCT", label: "HealthyCT" },
    { value: "horizonHealthCare", label: "Horizon Healthcare" },
    { value: "humana", label: "Humana" },
    { value: "magellan", label: "Magellan" },
    { value: "massHealth", label: "MassHealth" },
    { value: "medicaid", label: "Medicaid" },
    { value: "medicare", label: "Medicare" },
    { value: "multiPlan", label: "MultiPlan" },
    { value: "neighborhoodHealth", label: "Neighborhood Health" },
    { value: "optum", label: "Optum" },
    { value: "seniorWholeHealth", label: "Senior Whole Health" },
    { value: "triCare", label: "TRICARE" },
    { value: "tufts", label: "Tufts" },
    { value: "unicare", label: "UniCare" },
    { value: "unitedHealthCareUhcUbh", label: "UnitedHealthcare UHC | UBH" },
    {
      value: "vaCommunityCareNetworkCcn",
      label: "VA Community Care Network CCN",
    },
  ],
};
